### ISSUE TITLE
Add check for system installed dart

### ISSUE THREAD

**Issue by srmainwaring** [gazebo-release/gz_dartsim_vendor#4]
## Feature request

Add a check for the system installed version of DART before calling `ament_vendor`. For example on macOS the appropriate DART libraries are available from `brew`:

```bash
brew info dartsim
==> dartsim: stable 6.13.2 (bottled)
Dynamic Animation and Robotics Toolkit
https://dartsim.github.io/
Installed
/opt/homebrew/Cellar/dartsim/6.13.2_3 (1,081 files, 48.0MB) *
  Poured from bottle on 2024-05-08 at 23:03:42
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/d/dartsim.rb
License: BSD-2-Clause
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: assimp ✔, bullet ✔, eigen ✔, fcl ✔, flann ✔, fmt ✔, ipopt ✔, libccd ✔, nlopt ✔, ode ✔, open-scene-graph ✔, spdlog ✔, tinyxml2 ✔, urdfdom ✔
```

and do not need to be built again as part of the `vendor` build.

A suggested change (with debug messages) in this branch: https://github.com/srmainwaring/gz_dartsim_vendor/tree/rolling-macos

**Comment by azeey** [comment]
That looks good to me. Can you create a PR?

**Comment by oysstu** [comment]
@srmainwaring Are you planning on following this up with a PR?
